=================================================

Milestone 3 

Name  : Arief Bagus Nugraha

Batch : RMT-013

=================================================

Link Presentasi 

https://www.canva.com/design/DAG_rzX_qXo/vshC0wVkRb98XO7VKf6E8w/edit?utm_content=DAG_rzX_qXo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

In [26]:
import pandas as pd
import great_expectations as gx

## Memuat Data

In [27]:
# Load Data
file_name = 'P2M3_arief_bagus_nugraha_data_raw.csv'
df = pd.read_csv(file_name)

# Tampilkan 5 baris pertama untuk memastikan data terbaca
df.head()

,Product_Id,Product_Name,Category,Discounted_Price,Actual_Price,Discount_Percentage,Rating,Rating_Count,About_Product,User_Id,User_Name,Review_Id,Review_Title,Review_Content,Img_Link,Product_Link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,64.0,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,43.0,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,90.0,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,53.0,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61.0,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [28]:
# Info Table
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Id           1465 non-null   object
 1   Product_Name         1465 non-null   object
 2   Category             1465 non-null   object
 3   Discounted_Price     1465 non-null   float64
 4   Actual_Price         1465 non-null   float64
 5   Discount_Percentage  1465 non-null   float64
 6   Rating               1464 non-null   float64
 7   Rating_Count         1463 non-null   object
 8   About_Product        1465 non-null   object
 9   User_Id              1465 non-null   object
 10  User_Name            1465 non-null   object
 11  Review_Id            1465 non-null   object
 12  Review_Title         1465 non-null   object
 13  Review_Content       1465 non-null   object
 14  Img_Link             1465 non-null   object
 15  Product_Link         1465 non-null   object
dtypes: float64(4), object(12)
memory usage: 183.3+ KB

## Persiapan untuk validasi

In [29]:
# Membuat Transaction_ID (Gabungan Product_Id + Index) agar Unik
df['Transaction_ID'] = df['Product_Id'] + '_' + df.index.astype(str)

# Mengmbil kategori utama saja (Split string dan ambil elemen pertama)
df['Main_Category'] = df['Category'].str.split('|').str[0]

# Memastikan Discounted_Price adalah float
df['Discounted_Price'] = df['Discounted_Price'].astype(float)

print("Preprocessing selesai. Kolom baru terbentuk.")
df[['Transaction_ID', 'Main_Category', 'Discounted_Price']].head()

Preprocessing selesai. Kolom baru terbentuk.

  Transaction_ID          Main_Category  Discounted_Price
0   B07JW9H4J1_0  Computers&Accessories             399.0
1   B098NS6PVG_1  Computers&Accessories             199.0
2   B096MSW6CT_2  Computers&Accessories             199.0
3   B08HDJ86NZ_3  Computers&Accessories             329.0
4   B08CF3B7N1_4  Computers&Accessories             154.0

In [30]:
#Info Tabel Baru
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Id           1465 non-null   object
 1   Product_Name         1465 non-null   object
 2   Category             1465 non-null   object
 3   Discounted_Price     1465 non-null   float64
 4   Actual_Price         1465 non-null   float64
 5   Discount_Percentage  1465 non-null   float64
 6   Rating               1464 non-null   float64
 7   Rating_Count         1463 non-null   object
 8   About_Product        1465 non-null   object
 9   User_Id              1465 non-null   object
 10  User_Name            1465 non-null   object
 11  Review_Id            1465 non-null   object
 12  Review_Title         1465 non-null   object
 13  Review_Content       1465 non-null   object
 14  Img_Link             1465 non-null   object
 15  Product_Link         1465 non-null   object
 16  Transaction_ID       1465 non-null   object
 17  Main_Category        1465 non-null   object
dtypes: float64(4), object(14)
memory usage: 206.1+ KB

## Inisialisasi Great Expectations

In [31]:
# Inisialisasi Data Context
context = gx.get_context()

# Membuat Validator dari DataFrame Pandas
validator = context.sources.pandas_default.read_dataframe(df)

print("Validator berhasil dibuat!")

Validator berhasil dibuat!

## Eksekusi Validasi

### Expectation 1 - Check Unique ID

In [38]:
# Validasi apakah kolom Transaction_ID benar-benar unik.
validation_result = validator.expect_column_values_to_be_unique('Transaction_ID')

print(f"Validation Success: {validation_result['success']}")
print(f"   Jumlah Data Dicek     : {validation_result['result']['element_count']}")
print(f"   Jumlah Duplikat (Fail): {validation_result['result']['unexpected_count']}")
print(f"   Persentase Duplikat   : {validation_result['result']['unexpected_percent']}%")

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Validation Success: True
   Jumlah Data Dicek     : 1465
   Jumlah Duplikat (Fail): 0
   Persentase Duplikat   : 0.0%

### Expectation 2 - Check Rating Range

In [36]:
# Validasi apakah Rating berada di antara 0 sampai 5.
validation_result = validator.expect_column_values_to_be_between(
    column='Rating', 
    min_value=0, 
    max_value=5
)

print(f"Validation Success    : {validation_result['success']}")
print(f"Jumlah Data Dicek     : {validation_result['result']['element_count']}")
print(f"Jumlah Fail           : {validation_result['result']['unexpected_count']}")

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Validation Success: True
   Jumlah Data Dicek     : 1465
   Jumlah Duplikat (Fail): 0
   Persentase Duplikat   : 0.0%

### Expectation 3 - Check Category Consistency

In [39]:
# Ambil daftar kategori unik dari data sebagai referensi set
# Validasi apakah Main_Category konsisten dengan daftar kategori yang ada di data saat ini.
valid_cats = list(df['Main_Category'].unique())

validation_result = validator.expect_column_values_to_be_in_set('Main_Category', valid_cats)

print(f"Validation Success : {validation_result['success']}")
print(f"Total Data Dicek   : {validation_result['result']['element_count']}")
print(f"Data Tidak Valid   : {validation_result['result']['unexpected_count']}")

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Validation Success: True
Total Data Dicek   : 1465
Data Tidak Valid   : 0

### Expectation 4 - Check Price Type (Harus Float)

In [41]:
validation_result = validator.expect_column_values_to_be_in_type_list(
    'Discounted_Price', 
    ['float', 'float64']
)

print(f"Validation Success: {validation_result['success']}")
print(f"Tipe Data Ditemukan: {validation_result['result']['observed_value']}")

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

Validation Success: True
Tipe Data Ditemukan: float64

### Expectation 5 - Check Product_Id Length (Expectation Tambahan)

In [42]:
#Panjang karakter Product_Id harus 10 digit.

validation_result = validator.expect_column_value_lengths_to_equal('Product_Id', 10)

print(f"Validation Success: {validation_result['success']}")
print(f"Jumlah Data Dicek : {validation_result['result']['element_count']}")
print(f"Jumlah Fail       : {validation_result['result']['unexpected_count']}")

Calculating Metrics:   0%|          | 0/9 [00:00<?, ?it/s]

Validation Success: True
Jumlah Data Dicek : 1465
Jumlah Fail       : 0

### Expectation 6 - Check ID Format (Regex) (Expectation Tambahan)

In [43]:
# Format ID hanya boleh Huruf Kapital dan Angka
validation_result = validator.expect_column_values_to_match_regex(
    'Product_Id', 
    r'^[A-Z0-9]+$'
)

print(f"Validation Success: {validation_result['success']}")
print(f"Jumlah Data Dicek : {validation_result['result']['element_count']}")
print(f"Jumlah Fail       : {validation_result['result']['unexpected_count']}")

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Validation Success: True
Jumlah Data Dicek : 1465
Jumlah Fail       : 0

### Expectation 7 - Check Row Count

In [19]:
# Jumlah baris harus di antara 100 dan 10.000. Untuk memastikan jumlah baris wajar (tidak terlalu sedikit atau kebanyakan).
validation_result = validator.expect_table_row_count_to_be_between(
    min_value=100, 
    max_value=10000
)

print(f"Validation Success: {validation_result['success']}")
print(f"Observed Row Count: {validation_result['result']['observed_value']}")

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

Validation Success: True
Observed Row Count: 1465